sonar.projectKey=food-donations-core
sonar.projectName=Food Donations Core
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/venv/**
sonar.python.file.suffixes=.py
